### ISSUE TITLE
Does not compile

### ISSUE THREAD

**Issue by jbrepogmailcom** [drandreas/lolin-d32-ulp-adc#1]
Hello, I get following compilation error. Is there anything I can fix? Arduino IDE 1.8.13
```
  File "/home/janbenes/.arduino15/packages/esp32/tools/ulptool/src/esp32ulp_build_recipe.py", line 560, in <module>
    main(sys.argv[1:])
  File "/home/janbenes/.arduino15/packages/esp32/tools/ulptool/src/esp32ulp_build_recipe.py", line 106, in main
    build_ulp(PATHS, ulp_files, board_options, True)
  File "/home/janbenes/.arduino15/packages/esp32/tools/ulptool/src/esp32ulp_build_recipe.py", line 137, in build_ulp
    proc = subprocess.Popen(cmd[1],stdout=subprocess.PIPE,stderr=subprocess.PIPE,shell=False)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
exit status 1
Error compiling for board ESP32 Dev Module.
```

The compilation line is
python /home/janbenes/.arduino15/packages/esp32/tools/ulptool/src/esp32ulp_build_recipe.py -DESP_PLATFORM "-DMBEDTLS_CONFIG_FILE=\"mbedtls/esp_config.h\"" -DHAVE_CONFIG_H -DGCC_NOT_5_2_0=0 -DWITH_POSIX -I/home/janbenes/.arduino15/packages/esp32/hardware/esp32/1.0.5/tools/sdk/include/config -I/home/janbenes/.arduino15/packages/esp32/hardware/esp32/1.0.5/tools/sdk/include/app_trace -I/home/janbenes/.arduino15/packages/esp32/hardware/esp32/1.0.5/tools/sdk/include/app_update -I/home/janbenes/.arduino15/packages/esp32/hardware/esp32/1.0.5/tools/sdk/include/asio -I/home/janbenes/.arduino15/packages/esp32/hardware/esp32/1.0.5/tools/sdk/include/bootloader_support -I/home/janbenes/.arduino15/packages/esp32/hardware/esp32/1.0.5/tools/sdk/include/bt -I/home/janbenes/.arduino15/packages/esp32/hardware/esp32/1.0.5/tools/sdk/include/coap -I/home/janbenes/.arduino15/packages/esp32/hardware/esp32/1.0.5/tools/sdk/include/console -I/home/janbenes/.arduino15/packages/esp32/hardware/esp32/1.0.5/tools/sdk/include/driver -I/home/janbenes/.arduino15/packages/esp32/hardware/esp32/1.0.5/tools/sdk/include/efuse -I/home/janbenes/.arduino15/packages/esp32/hardware/esp32/1.0.5/tools/sdk/include/esp-tls -I/home/janbenes/.arduino15/packages/esp32/hardware/esp32/1.0.5/tools/sdk/include/esp32 -I/home/janbenes/.arduino15/packages/esp32/hardware/esp32/1.0.5/tools/sdk/include/esp_adc_cal -I/home/janbenes/.arduino15/packages/esp32/hardware/esp32/1.0.5/tools/sdk/include/esp_event -I/home/janbenes/.arduino15/packages/esp32/hardware/esp32/1.0.5/tools/sdk/include/esp_http_client -I/home/janbenes/.arduino15/packages/esp32/hardware/esp32/1.0.5/tools/sdk/include/esp_http_server -I/home/janbenes/.arduino15/packages/esp32/hardware/esp32/1.0.5/tools/sdk/include/esp_https_ota -I/home/janbenes/.arduino15/packages/esp32/hardware/esp32/1.0.5/tools/sdk/include/esp_https_server -I/home/janbenes/.arduino15/packages/esp32/hardware/esp32/1.0.5/tools/sdk/include/esp_ringbuf -I/home/janbenes/.arduino15/packages/esp32/hardware/esp32/1.0.5/tools/sdk/include/esp_websocket_client -I/home/janbenes/.arduino15/packages/esp32/hardware/esp32/1.0.5/tools/sdk/include/espcoredump -I/home/janbenes/.arduino15/packages/esp32/hardware/esp32/1.0.5/tools/sdk/include/ethernet -I/home/janbenes/.arduino15/packages/esp32/hardware/esp32/1.0.5/tools/sdk/include/expat -I/home/janbenes/.arduino15/packages/esp32/hardware/esp32/1.0.5/tools/sdk/include/fatfs -I/home/janbenes/.arduino15/packages/esp32/hardware/esp32/1.0.5/tools/sdk/include/freemodbus -I/home/janbenes/.arduino15/packages/esp32/hardware/esp32/1.0.5/tools/sdk/include/freertos -I/home/janbenes/.arduino15/packages/esp32/hardware/esp32/1.0.5/tools/sdk/include/heap -I/home/janbenes/.arduino15/packages/esp32/hardware/esp32/1.0.5/tools/sdk/include/idf_test -I/home/janbenes/.arduino15/packages/esp32/hardware/esp32/1.0.5/tools/sdk/include/jsmn -I/home/janbenes/.arduino15/packages/esp32/hardware/esp32/1.0.5/tools/sdk/include/json -I/home/janbenes/.arduino15/packages/esp32/hardware/esp32/1.0.5/tools/sdk/include/libsodium -I/home/janbenes/.arduino15/packages/esp32/hardware/esp32/1.0.5/tools/sdk/include/log -I/home/janbenes/.arduino15/packages/esp32/hardware/esp32/1.0.5/tools/sdk/include/lwip -I/home/janbenes/.arduino15/packages/esp32/hardware/esp32/1.0.5/tools/sdk/include/mbedtls -I/home/janbenes/.arduino15/packages/esp32/hardware/esp32/1.0.5/tools/sdk/include/mdns -I/home/janbenes/.arduino15/packages/esp32/hardware/esp32/1.0.5/tools/sdk/include/micro-ecc -I/home/janbenes/.arduino15/packages/esp32/hardware/esp32/1.0.5/tools/sdk/include/mqtt -I/home/janbenes/.arduino15/packages/esp32/hardware/esp32/1.0.5/tools/sdk/include/newlib -I/home/janbenes/.arduino15/packages/esp32/hardware/esp32/1.0.5/tools/sdk/include/nghttp -I/home/janbenes/.arduino15/packages/esp32/hardware/esp32/1.0.5/tools/sdk/include/nimble -I/home/janbenes/.arduino15/packages/esp32/hardware/esp32/1.0.5/tools/sdk/include/nvs_flash -I/home/janbenes/.arduino15/packages/esp32/hardware/esp32/1.0.5/tools/sdk/include/openssl -I/home/janbenes/.arduino15/packages/esp32/hardware/esp32/1.0.5/tools/sdk/include/protobuf-c -I/home/janbenes/.arduino15/packages/esp32/hardware/esp32/1.0.5/tools/sdk/include/protocomm -I/home/janbenes/.arduino15/packages/esp32/hardware/esp32/1.0.5/tools/sdk/include/pthread -I/home/janbenes/.arduino15/packages/esp32/hardware/esp32/1.0.5/tools/sdk/include/sdmmc -I/home/janbenes/.arduino15/packages/esp32/hardware/esp32/1.0.5/tools/sdk/include/smartconfig_ack -I/home/janbenes/.arduino15/packages/esp32/hardware/esp32/1.0.5/tools/sdk/include/soc -I/home/janbenes/.arduino15/packages/esp32/hardware/esp32/1.0.5/tools/sdk/include/spi_flash -I/home/janbenes/.arduino15/packages/esp32/hardware/esp32/1.0.5/tools/sdk/include/spiffs -I/home/janbenes/.arduino15/packages/esp32/hardware/esp32/1.0.5/tools/sdk/include/tcp_transport -I/home/janbenes/.arduino15/packages/esp32/hardware/esp32/1.0.5/tools/sdk/include/tcpip_adapter -I/home/janbenes/.arduino15/packages/esp32/hardware/esp32/1.0.5/tools/sdk/include/ulp -I/home/janbenes/.arduino15/packages/esp32/hardware/esp32/1.0.5/tools/sdk/include/unity -I/home/janbenes/.arduino15/packages/esp32/hardware/esp32/1.0.5/tools/sdk/include/vfs -I/home/janbenes/.arduino15/packages/esp32/hardware/esp32/1.0.5/tools/sdk/include/wear_levelling -I/home/janbenes/.arduino15/packages/esp32/hardware/esp32/1.0.5/tools/sdk/include/wifi_provisioning -I/home/janbenes/.arduino15/packages/esp32/hardware/esp32/1.0.5/tools/sdk/include/wpa_supplicant -I/home/janbenes/.arduino15/packages/esp32/hardware/esp32/1.0.5/tools/sdk/include/xtensa-debug-module -I/home/janbenes/.arduino15/packages/esp32/hardware/esp32/1.0.5/tools/sdk/include/esp-face -I/home/janbenes/.arduino15/packages/esp32/hardware/esp32/1.0.5/tools/sdk/include/esp32-camera -I/home/janbenes/.arduino15/packages/esp32/hardware/esp32/1.0.5/tools/sdk/include/esp-face -I/home/janbenes/.arduino15/packages/esp32/hardware/esp32/1.0.5/tools/sdk/include/fb_gfx -b /tmp/arduino_build_278464 -p /home/janbenes/.arduino15/packages/esp32/hardware/esp32/1.0.5 -u /home/janbenes/.arduino15/packages/esp32/tools/ulptool/src/esp32ulp-elf-binutils/bin/ -x /home/janbenes/.arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/1.22.0-97-gc752ad5-5.2.0/bin/ -t /home/janbenes/.arduino15/packages/esp32/tools/ulptool/src/ --DF_CPU=240000000L --DARDUINO=10813 --DARDUINO_=ESP32_DEV --DARDUINO_ARCH_=ESP32 "--DARDUINO_BOARD=\"ESP32_DEV\"" "--DARDUINO_VARIANT=\"esp32\""
/home/janbenes/.arduino15/packages/esp32/tools/ulptool/src/ulpcc/bin/linux/lcc -I/home/janbenes/.arduino15/packages/esp32/hardware/esp32/1.0.5/tools/sdk/include/soc/soc -I/home/janbenes/.arduino15/packages/esp32/hardware/esp32/1.0.5/tools/sdk/include/soc -I/home/janbenes/.arduino15/packages/esp32/tools/ulptool/src/ulpcc/include -D_ULPCC_ -lccdir=/home/janbenes/.arduino15/packages/esp32/tools/ulptool/src/ulpcc/bin/linux -Wf-target=ulp -S ulp_code.c -o ulp_code.sTraceback (most recent call last):

**Comment by drandreas** [comment]
Do the ULP examples compile on your system?
https://github.com/duff2013/ulptool/tree/master/src/ulp_examples

**Comment by jbrepogmailcom** [comment]
No, that is the example I am testing on: https://github.com/duff2013/ulptool/tree/master/src/ulp_examples/ulp_adc

**Comment by jbrepogmailcom** [comment]
But I am getting other error:

/home/janbenes/.arduino15/packages/esp32/tools/ulptool/src/esp32ulp-elf-binutils/bin/esp32ulp-elf-ld: ulp_main.elf section `.data' will not fit in region `ram'_main.common.ld adc.ulp.o
/home/janbenes/.arduino15/packages/esp32/tools/ulptool/src/esp32ulp-elf-binutils/bin/esp32ulp-elf-ld: region `ram' overflowed by 88 bytes

exit status 1
Error compiling for board ESP32 Dev Module.

I tried to change ULP memory to 1024 and to 4096, but still get exactly same error.

**Comment by drandreas** [comment]
strange, I'will try to find a slot to test my code with the latest ide in the next couple of days.
